# Workflow name
name: "Chromaatic Deployment"

# Event for the workflow
on: push

# List of jobs
jobs:
  test:
    # Operating Systems
    runs-on: ubuntu-latest
    #Job steps
    steps:
      - uses: actions/checkout@v1
      - run: yarn
        #ðŸ‘‡ Adds Chromatic as a step in the workflow
      - uses: chromaui/action@v1
        # Options required for Chromatic's GitHubAction
        with:
          #ðŸ‘‡ Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy/ to obtain it
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
